### PR TITLE
Add classification notebooks

### PR DESCRIPTION
**Pull request by slushiegoose**
P1 - Logistic Regression
P2 - K-means
P3 - SVM & Decision Trees

### CODE REVIEW

**Review by angela24680403 — COMMENTED** [review]
We're gonna do kmeans last so pls change that to p3 and svm/decision tree to p2.

**Review by angela24680403 — APPROVED** [review]
Looks good!

**Comment by OscarL63** [comment]
Looks amazing ❤️

**Comment by angela24680403** [comment]
@OscarL63 yo why are you here??

**Pull request merged**
